services:
  - type: web
    name: deriv-volatility-monitor
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DERIV_API_TOKEN
        sync: false
      - key: DB_CLIENT
        value: sqlite
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL
        sync: false

